import json
import os

SURAHS = [
    {"number": 1, "name_bn": "আল-ফাতিহা", "name_ar": "الفاتحة", "name_en": "Al-Fatihah", "page": 1, "total_ayahs": 7, "type": "মাক্কী", "juz": 1},
    {"number": 2, "name_bn": "আল-বাকারাহ", "name_ar": "البقرة", "name_en": "Al-Baqarah", "page": 2, "total_ayahs": 286, "type": "মাদানী", "juz": 1},
    {"number": 3, "name_bn": "আলে-ইমরান", "name_ar": "آل عمران", "name_en": "Ali 'Imran", "page": 49, "total_ayahs": 200, "type": "মাদানী", "juz": 3},
    {"number": 4, "name_bn": "আন-নিসা", "name_ar": "النساء", "name_en": "An-Nisa", "page": 76, "total_ayahs": 176, "type": "মাদানী", "juz": 4},
    {"number": 5, "name_bn": "আল-মায়িদাহ", "name_ar": "المائدة", "name_en": "Al-Ma'idah", "page": 105, "total_ayahs": 120, "type": "মাদানী", "juz": 6},
    {"number": 6, "name_bn": "আল-আনআম", "name_ar": "الأنعام", "name_en": "Al-An'am", "page": 127, "total_ayahs": 165, "type": "মাক্কী", "juz": 7},
    {"number": 7, "name_bn": "আল-আ'রাফ", "name_ar": "الأعراف", "name_en": "Al-A'raf", "page": 150, "total_ayahs": 206, "type": "মাক্কী", "juz": 8},
    {"number": 8, "name_bn": "আল-আনফাল", "name_ar": "الأنفال", "name_en": "Al-Anfal", "page": 176, "total_ayahs": 75, "type": "মাদানী", "juz": 9},
    {"number": 9, "name_bn": "আত-তাওবাহ", "name_ar": "التوبة", "name_en": "At-Tawbah", "page": 186, "total_ayahs": 129, "type": "মাদানী", "juz": 10},
    {"number": 10, "name_bn": "ইউনুস", "name_ar": "يونس", "name_en": "Yunus", "page": 207, "total_ayahs": 109, "type": "মাক্কী", "juz": 11},
    {"number": 11, "name_bn": "হূদ", "name_ar": "هود", "name_en": "Hud", "page": 220, "total_ayahs": 123, "type": "মাক্কী", "juz": 11},
    {"number": 12, "name_bn": "ইউসুফ", "name_ar": "يوسف", "name_en": "Yusuf", "page": 234, "total_ayahs": 111, "type": "মাক্কী", "juz": 12},
    {"number": 13, "name_bn": "আর-রাদ", "name_ar": "الرعد", "name_en": "Ar-Ra'd", "page": 248, "total_ayahs": 43, "type": "মাদানী", "juz": 13},
    {"number": 14, "name_bn": "ইবরাহীম", "name_ar": "إبراهيم", "name_en": "Ibrahim", "page": 254, "total_ayahs": 52, "type": "মাক্কী", "juz": 13},
    {"number": 15, "name_bn": "আল-হিজর", "name_ar": "الحجر", "name_en": "Al-Hijr", "page": 261, "total_ayahs": 99, "type": "মাক্কী", "juz": 14},
    {"number": 16, "name_bn": "আন-নাহল", "name_ar": "النحل", "name_en": "An-Nahl", "page": 266, "total_ayahs": 128, "type": "মাক্কী", "juz": 14},
    {"number": 17, "name_bn": "বনী ইসরাঈল (আল-ইসরা)", "name_ar": "الإسراء", "name_en": "Al-Isra", "page": 281, "total_ayahs": 111, "type": "মাক্কী", "juz": 15},
    {"number": 18, "name_bn": "আল-কাহফ", "name_ar": "الكهف", "name_en": "Al-Kahf", "page": 292, "total_ayahs": 110, "type": "মাক্কী", "juz": 15},
    {"number": 19, "name_bn": "মারইয়াম", "name_ar": "مريم", "name_en": "Maryam", "page": 304, "total_ayahs": 98, "type": "মাক্কী", "juz": 16},
    {"number": 20, "name_bn": "ত্বা-হা", "name_ar": "طه", "name_en": "Ta-Ha", "page": 311, "total_ayahs": 135, "type": "মাক্কী", "juz": 16},
    {"number": 21, "name_bn": "আল-আম্বিয়া", "name_ar": "الأنبياء", "name_en": "Al-Anbiya", "page": 321, "total_ayahs": 112, "type": "মাক্কী", "juz": 17},
    {"number": 22, "name_bn": "আল-হজ্জ", "name_ar": "الحج", "name_en": "Al-Hajj", "page": 331, "total_ayahs": 78, "type": "মাদানী", "juz": 17},
    {"number": 23, "name_bn": "আল-মুমিনুন", "name_ar": "المؤمنون", "name_en": "Al-Mu'minun", "page": 341, "total_ayahs": 118, "type": "মাক্কী", "juz": 18},
    {"number": 24, "name_bn": "আন-নূর", "name_ar": "النور", "name_en": "An-Nur", "page": 349, "total_ayahs": 64, "type": "মাদানী", "juz": 18},
    {"number": 25, "name_bn": "আল-ফুরকান", "name_ar": "الفرقان", "name_en": "Al-Furqan", "page": 358, "total_ayahs": 77, "type": "মাক্কী", "juz": 18},
    {"number": 26, "name_bn": "আশ-শুআরা", "name_ar": "الشعراء", "name_en": "Ash-Shu'ara", "page": 366, "total_ayahs": 227, "type": "মাক্কী", "juz": 19},
    {"number": 27, "name_bn": "আন-নামল", "name_ar": "النمل", "name_en": "An-Naml", "page": 376, "total_ayahs": 93, "type": "মাক্কী", "juz": 19},
    {"number": 28, "name_bn": "আল-কাসাস", "name_ar": "القصص", "name_en": "Al-Qasas", "page": 384, "total_ayahs": 88, "type": "মাক্কী", "juz": 20},
    {"number": 29, "name_bn": "আল-আনকাবুত", "name_ar": "العنكبوت", "name_en": "Al-'Ankabut", "page": 395, "total_ayahs": 69, "type": "মাক্কী", "juz": 20},
    {"number": 30, "name_bn": "আর-রূম", "name_ar": "الروم", "name_en": "Ar-Rum", "page": 403, "total_ayahs": 60, "type": "মাক্কী", "juz": 21},
    {"number": 31, "name_bn": "লুকমান", "name_ar": "لقمان", "name_en": "Luqman", "page": 410, "total_ayahs": 34, "type": "মাক্কী", "juz": 21},
    {"number": 32, "name_bn": "আস-সাজদাহ", "name_ar": "السجدة", "name_en": "As-Sajdah", "page": 414, "total_ayahs": 30, "type": "মাক্কী", "juz": 21},
    {"number": 33, "name_bn": "আল-আহযাব", "name_ar": "الأحزاب", "name_en": "Al-Ahzab", "page": 417, "total_ayahs": 73, "type": "মাদানী", "juz": 21},
    {"number": 34, "name_bn": "সাবা", "name_ar": "سبأ", "name_en": "Saba", "page": 427, "total_ayahs": 54, "type": "মাক্কী", "juz": 22},
    {"number": 35, "name_bn": "ফাতির", "name_ar": "فاطر", "name_en": "Fatir", "page": 433, "total_ayahs": 45, "type": "মাক্কী", "juz": 22},
    {"number": 36, "name_bn": "ইয়াসীন", "name_ar": "يس", "name_en": "Ya-Sin", "page": 439, "total_ayahs": 83, "type": "মাক্কী", "juz": 22},
    {"number": 37, "name_bn": "আস-সাফফাত", "name_ar": "الصافات", "name_en": "As-Saffat", "page": 445, "total_ayahs": 182, "type": "মাক্কী", "juz": 23},
    {"number": 38, "name_bn": "ছোয়াদ", "name_ar": "ص", "name_en": "Sad", "page": 452, "total_ayahs": 88, "type": "মাক্কী", "juz": 23},
    {"number": 39, "name_bn": "আয-যুমার", "name_ar": "الزمر", "name_en": "Az-Zumar", "page": 457, "total_ayahs": 75, "type": "মাক্কী", "juz": 23},
    {"number": 40, "name_bn": "মু'মিন (গাফির)", "name_ar": "غافر", "name_en": "Ghafir", "page": 466, "total_ayahs": 85, "type": "মাক্কী", "juz": 24},
    {"number": 41, "name_bn": "ফুসসিলাত (হা-মীম সাজদাহ)", "name_ar": "فصلت", "name_en": "Fussilat", "page": 476, "total_ayahs": 54, "type": "মাক্কী", "juz": 24},
    {"number": 42, "name_bn": "আশ-শুরা", "name_ar": "الشورى", "name_en": "Ash-Shura", "page": 482, "total_ayahs": 53, "type": "মাক্কী", "juz": 25},
    {"number": 43, "name_bn": "আয-যুখরুফ", "name_ar": "الزخرف", "name_en": "Az-Zukhruf", "page": 488, "total_ayahs": 89, "type": "মাক্কী", "juz": 25},
    {"number": 44, "name_bn": "আদ-দুখান", "name_ar": "الدخان", "name_en": "Ad-Dukhan", "page": 495, "total_ayahs": 59, "type": "মাক্কী", "juz": 25},
    {"number": 45, "name_bn": "আল-জাসিয়া", "name_ar": "الجاثية", "name_en": "Al-Jathiyah", "page": 498, "total_ayahs": 37, "type": "মাক্কী", "juz": 25},
    {"number": 46, "name_bn": "আল-আহকাফ", "name_ar": "الأحقاف", "name_en": "Al-Ahqaf", "page": 501, "total_ayahs": 35, "type": "মাক্কী", "juz": 26},
    {"number": 47, "name_bn": "মুহাম্মদ", "name_ar": "محمد", "name_en": "Muhammad", "page": 506, "total_ayahs": 38, "type": "মাদানী", "juz": 26},
    {"number": 48, "name_bn": "আল-ফাতহ", "name_ar": "الفتح", "name_en": "Al-Fath", "page": 510, "total_ayahs": 29, "type": "মাদানী", "juz": 26},
    {"number": 49, "name_bn": "আল-হুজুরাত", "name_ar": "الحجرات", "name_en": "Al-Hujurat", "page": 514, "total_ayahs": 18, "type": "মাদানী", "juz": 26},
    {"number": 50, "name_bn": "ক্বাফ", "name_ar": "ق", "name_en": "Qaf", "page": 517, "total_ayahs": 45, "type": "মাক্কী", "juz": 26},
    {"number": 51, "name_bn": "আয-যারিয়াত", "name_ar": "الذاريات", "name_en": "Adh-Dhariyat", "page": 519, "total_ayahs": 60, "type": "মাক্কী", "juz": 26},
    {"number": 52, "name_bn": "আত-তুর", "name_ar": "الطور", "name_en": "At-Tur", "page": 522, "total_ayahs": 49, "type": "মাক্কী", "juz": 27},
    {"number": 53, "name_bn": "আন-নাজম", "name_ar": "النجم", "name_en": "An-Najm", "page": 525, "total_ayahs": 62, "type": "মাক্কী", "juz": 27},
    {"number": 54, "name_bn": "আল-ক্বামার", "name_ar": "القمر", "name_en": "Al-Qamar", "page": 527, "total_ayahs": 55, "type": "মাক্কী", "juz": 27},
    {"number": 55, "name_bn": "আর-রাহমান", "name_ar": "الرحمن", "name_en": "Ar-Rahman", "page": 530, "total_ayahs": 78, "type": "মাদানী", "juz": 27},
    {"number": 56, "name_bn": "আল-ওয়াকিয়া", "name_ar": "الواقعة", "name_en": "Al-Waqi'ah", "page": 533, "total_ayahs": 96, "type": "মাক্কী", "juz": 27},
    {"number": 57, "name_bn": "আল-হাদীদ", "name_ar": "الحديد", "name_en": "Al-Hadid", "page": 536, "total_ayahs": 29, "type": "মাদানী", "juz": 27},
    {"number": 58, "name_bn": "আল-মুজাদালাহ", "name_ar": "المجادلة", "name_en": "Al-Mujadilah", "page": 541, "total_ayahs": 22, "type": "মাদানী", "juz": 28},
    {"number": 59, "name_bn": "আল-হাশর", "name_ar": "الحشر", "name_en": "Al-Hashr", "page": 544, "total_ayahs": 24, "type": "মাদানী", "juz": 28},
    {"number": 60, "name_bn": "আল-মুমতাহিনা", "name_ar": "الممتحنة", "name_en": "Al-Mumtahanah", "page": 548, "total_ayahs": 13, "type": "মাদানী", "juz": 28},
    {"number": 61, "name_bn": "আস-সফ", "name_ar": "الصف", "name_en": "As-Saff", "page": 550, "total_ayahs": 14, "type": "মাদানী", "juz": 28},
    {"number": 62, "name_bn": "আল-জুমুআহ", "name_ar": "الجمعة", "name_en": "Al-Jumu'ah", "page": 552, "total_ayahs": 11, "type": "মাদানী", "juz": 28},
    {"number": 63, "name_bn": "আল-মুনাফিকুন", "name_ar": "المنافقون", "name_en": "Al-Munafiqun", "page": 553, "total_ayahs": 11, "type": "মাদানী", "juz": 28},
    {"number": 64, "name_bn": "আত-তাগাবুন", "name_ar": "التغابن", "name_en": "At-Taghabun", "page": 555, "total_ayahs": 18, "type": "মাদানী", "juz": 28},
    {"number": 65, "name_bn": "আত-ত্বালাক্ব", "name_ar": "الطلاق", "name_en": "At-Talaq", "page": 557, "total_ayahs": 12, "type": "মাদানী", "juz": 28},
    {"number": 66, "name_bn": "আত-তাহরীম", "name_ar": "التحريم", "name_en": "At-Tahrim", "page": 559, "total_ayahs": 12, "type": "মাদানী", "juz": 28},
    {"number": 67, "name_bn": "আল-মুলক", "name_ar": "الملك", "name_en": "Al-Mulk", "page": 561, "total_ayahs": 30, "type": "মাক্কী", "juz": 29},
    {"number": 68, "name_bn": "আল-ক্বলম", "name_ar": "القلم", "name_en": "Al-Qalam", "page": 563, "total_ayahs": 52, "type": "মাক্কী", "juz": 29},
    {"number": 69, "name_bn": "আল-হাক্বক্বাহ", "name_ar": "الحاقة", "name_en": "Al-Haqqah", "page": 565, "total_ayahs": 52, "type": "মাক্কী", "juz": 29},
    {"number": 70, "name_bn": "আল-মাআরিজ", "name_ar": "المعارج", "name_en": "Al-Ma'arij", "page": 567, "total_ayahs": 44, "type": "মাক্কী", "juz": 29},
    {"number": 71, "name_bn": "নূহ", "name_ar": "نوح", "name_en": "Nuh", "page": 569, "total_ayahs": 28, "type": "মাক্কী", "juz": 29},
    {"number": 72, "name_bn": "আল-জ্বিন", "name_ar": "الجن", "name_en": "Al-Jinn", "page": 571, "total_ayahs": 28, "type": "মাক্কী", "juz": 29},
    {"number": 73, "name_bn": "আল-মুযযাম্মিল", "name_ar": "المزمل", "name_en": "Al-Muzzammil", "page": 573, "total_ayahs": 20, "type": "মাক্কী", "juz": 29},
    {"number": 74, "name_bn": "আল-মুদ্দাসসির", "name_ar": "المدثر", "name_en": "Al-Muddaththir", "page": 574, "total_ayahs": 56, "type": "মাক্কী", "juz": 29},
    {"number": 75, "name_bn": "আল-ক্বিয়ামাহ", "name_ar": "القيامة", "name_en": "Al-Qiyamah", "page": 576, "total_ayahs": 40, "type": "মাক্কী", "juz": 29},
    {"number": 76, "name_bn": "আল-ইনসান (আদ-দাহর)", "name_ar": "الإنسان", "name_en": "Al-Insan", "page": 577, "total_ayahs": 31, "type": "মাদানী", "juz": 29},
    {"number": 77, "name_bn": "আল-মুরসালাত", "name_ar": "المرسلات", "name_en": "Al-Mursalat", "page": 579, "total_ayahs": 50, "type": "মাক্কী", "juz": 29},
    {"number": 78, "name_bn": "আন-নাবা", "name_ar": "النبأ", "name_en": "An-Naba", "page": 581, "total_ayahs": 40, "type": "মাক্কী", "juz": 30},
    {"number": 79, "name_bn": "আন-নাযিআত", "name_ar": "النازعات", "name_en": "An-Nazi'at", "page": 582, "total_ayahs": 46, "type": "মাক্কী", "juz": 30},
    {"number": 80, "name_bn": "আবাসা", "name_ar": "عبس", "name_en": "'Abasa", "page": 584, "total_ayahs": 42, "type": "মাক্কী", "juz": 30},
    {"number": 81, "name_bn": "আত-তাকভীর", "name_ar": "التكوير", "name_en": "At-Takwir", "page": 585, "total_ayahs": 29, "type": "মাক্কী", "juz": 30},
    {"number": 82, "name_bn": "আল-ইনফিতার", "name_ar": "الانفطار", "name_en": "Al-Infitar", "page": 586, "total_ayahs": 19, "type": "মাক্কী", "juz": 30},
    {"number": 83, "name_bn": "আল-মুতাফফিফীন", "name_ar": "المطففين", "name_en": "Al-Mutaffifin", "page": 587, "total_ayahs": 36, "type": "মাক্কী", "juz": 30},
    {"number": 84, "name_bn": "আল-ইনশিকাক্ব", "name_ar": "الانشقاق", "name_en": "Al-Inshiqaq", "page": 588, "total_ayahs": 25, "type": "মাক্কী", "juz": 30},
    {"number": 85, "name_bn": "আল-বুরূজ", "name_ar": "البروج", "name_en": "Al-Buruj", "page": 589, "total_ayahs": 22, "type": "মাক্কী", "juz": 30},
    {"number": 86, "name_bn": "আত-ত্বারিক্ব", "name_ar": "الطارق", "name_en": "At-Tariq", "page": 590, "total_ayahs": 17, "type": "মাক্কী", "juz": 30},
    {"number": 87, "name_bn": "আল-আ'লা", "name_ar": "الأعلى", "name_en": "Al-A'la", "page": 591, "total_ayahs": 19, "type": "মাক্কী", "juz": 30},
    {"number": 88, "name_bn": "আল-গাশিয়াহ", "name_ar": "الغاشية", "name_en": "Al-Ghashiyah", "page": 591, "total_ayahs": 26, "type": "মাক্কী", "juz": 30},
    {"number": 89, "name_bn": "আল-ফজর", "name_ar": "الفجر", "name_en": "Al-Fajr", "page": 592, "total_ayahs": 30, "type": "মাক্কী", "juz": 30},
    {"number": 90, "name_bn": "আল-বালাদ", "name_ar": "البلد", "name_en": "Al-Balad", "page": 593, "total_ayahs": 20, "type": "মাক্কী", "juz": 30},
    {"number": 91, "name_bn": "আশ-শামস", "name_ar": "الشمس", "name_en": "Ash-Shams", "page": 594, "total_ayahs": 15, "type": "মাক্কী", "juz": 30},
    {"number": 92, "name_bn": "আল-লায়ল", "name_ar": "الليل", "name_en": "Al-Layl", "page": 594, "total_ayahs": 21, "type": "মাক্কী", "juz": 30},
    {"number": 93, "name_bn": "আদ-দুহা", "name_ar": "الضحى", "name_en": "Ad-Duha", "page": 595, "total_ayahs": 11, "type": "মাক্কী", "juz": 30},
    {"number": 94, "name_bn": "আল-ইনশিরাহ (শারহ)", "name_ar": "الشرح", "name_en": "Ash-Sharh", "page": 595, "total_ayahs": 8, "type": "মাক্কী", "juz": 30},
    {"number": 95, "name_bn": "আত-তীন", "name_ar": "التين", "name_en": "At-Tin", "page": 596, "total_ayahs": 8, "type": "মাক্কী", "juz": 30},
    {"number": 96, "name_bn": "আল-আলাক্ব", "name_ar": "العلق", "name_en": "Al-'Alaq", "page": 596, "total_ayahs": 19, "type": "মাক্কী", "juz": 30},
    {"number": 97, "name_bn": "আল-ক্বদর", "name_ar": "القدر", "name_en": "Al-Qadr", "page": 597, "total_ayahs": 5, "type": "মাক্কী", "juz": 30},
    {"number": 98, "name_bn": "আল-বাইয়্যিনাহ", "name_ar": "البينة", "name_en": "Al-Bayyinah", "page": 597, "total_ayahs": 8, "type": "মাদানী", "juz": 30},
    {"number": 99, "name_bn": "আল-যিলযাল", "name_ar": "الزلزلة", "name_en": "Az-Zalzalah", "page": 598, "total_ayahs": 8, "type": "মাদানী", "juz": 30},
    {"number": 100, "name_bn": "আল-আদিয়াত", "name_ar": "العاديات", "name_en": "Al-'Adiyat", "page": 598, "total_ayahs": 11, "type": "মাক্কী", "juz": 30},
    {"number": 101, "name_bn": "আল-ক্বারিআহ", "name_ar": "القارعة", "name_en": "Al-Qari'ah", "page": 599, "total_ayahs": 11, "type": "মাক্কী", "juz": 30},
    {"number": 102, "name_bn": "আত-তাকাসুর", "name_ar": "التكاثر", "name_en": "At-Takathur", "page": 599, "total_ayahs": 8, "type": "মাক্কী", "juz": 30},
    {"number": 103, "name_bn": "আল-আসর", "name_ar": "العصر", "name_en": "Al-'Asr", "page": 600, "total_ayahs": 3, "type": "মাক্কী", "juz": 30},
    {"number": 104, "name_bn": "আল-হুমাযাহ", "name_ar": "الهمزة", "name_en": "Al-Humazah", "page": 600, "total_ayahs": 9, "type": "মাক্কী", "juz": 30},
    {"number": 105, "name_bn": "আল-ফীল", "name_ar": "الفيل", "name_en": "Al-Fil", "page": 600, "total_ayahs": 5, "type": "মাক্কী", "juz": 30},
    {"number": 106, "name_bn": "কুরাইশ", "name_ar": "قريش", "name_en": "Quraysh", "page": 601, "total_ayahs": 4, "type": "মাক্কী", "juz": 30},
    {"number": 107, "name_bn": "আল-মাউন", "name_ar": "الماعون", "name_en": "Al-Ma'un", "page": 601, "total_ayahs": 7, "type": "মাক্কী", "juz": 30},
    {"number": 108, "name_bn": "আল-কাউসার", "name_ar": "الكوثر", "name_en": "Al-Kawthar", "page": 601, "total_ayahs": 3, "type": "মাক্কী", "juz": 30},
    {"number": 109, "name_bn": "আল-কাফিরুন", "name_ar": "الكافرون", "name_en": "Al-Kafirun", "page": 602, "total_ayahs": 6, "type": "মাক্কী", "juz": 30},
    {"number": 110, "name_bn": "আন-নাসর", "name_ar": "النصر", "name_en": "An-Nasr", "page": 602, "total_ayahs": 3, "type": "মাদানী", "juz": 30},
    {"number": 111, "name_bn": "আল-লাহাব (আল-মাসাদ)", "name_ar": "المسد", "name_en": "Al-Masad", "page": 602, "total_ayahs": 5, "type": "মাক্কী", "juz": 30},
    {"number": 112, "name_bn": "আল-ইখলাস", "name_ar": "الإخلاص", "name_en": "Al-Ikhlas", "page": 603, "total_ayahs": 4, "type": "মাক্কী", "juz": 30},
    {"number": 113, "name_bn": "আল-ফালাক্ব", "name_ar": "الفلق", "name_en": "Al-Falaq", "page": 603, "total_ayahs": 5, "type": "মাক্কী", "juz": 30},
    {"number": 114, "name_bn": "আন-নাস", "name_ar": "الناس", "name_en": "An-Nas", "page": 603, "total_ayahs": 6, "type": "মাক্কী", "juz": 30}
]

from generate_metadata import PARAS, MANZILS, MUSABBAHAT, SAJDAHS

data = {
    "total_pages": 611,
    "paras": PARAS,
    "surahs": SURAHS,
    "manzils": MANZILS,
    "musabbahat": MUSABBAHAT,
    "sajdahs": SAJDAHS
}

os.makedirs("public/data", exist_ok=True)
with open("public/data/quran_metadata.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("quran_metadata.json successfully created!")
